### ISSUE TITLE
Source code modifield mq135 library?

### ISSUE THREAD

**Issue by w4solutions** [zesteros/ArduinoAirQualityMonitor2#1]
Have modifield mq135 library??

**Comment by zesteros** [comment]
Yes it is, I have to, because the native library does not give all values, also I compared the given values with the air monitor of goverment of my country and the reading of the carbon monoxide for example, looks like the federal monitor. A thing that I saw in the MQ135 Library of GeorK is the resistance conversion, he put a unnecessary five  in the formula, but that doesn't affect the gas reading. I have forked the GeorgK repository, and I have modified several methods. You can see this changes here:
[(https://github.com/zesteros/MQ135/commits/master)]

**Comment by w4solutions** [comment]
Thanks!
